// Generated by CoffeeScript 2.4.1
"use strict";

(function () {
  document.getElementById('hero').innerHTML = "<div class=\"container\" id=\"logo\">\n<h1 class=\"title grey\">Vertical</h1>\n<h2 class=\"subtitle grey\">New verticle line every second...</h2>\n</div>";
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImhlcm8uY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztBQUFBLENBQUEsWUFBQTtBQUFBLEVBQUEsUUFBUSxDQUFSLGNBQUEsQ0FBQSxNQUFBLEVBQUEsU0FBQSxHQUE0QywySkFBNUM7Q0FBQSxFLElBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVybycpLmlubmVySFRNTCA9IFwiXCJcIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIiBpZD1cImxvZ29cIj5cbiAgPGgxIGNsYXNzPVwidGl0bGUgZ3JleVwiPlZlcnRpY2FsPC9oMT5cbiAgPGgyIGNsYXNzPVwic3VidGl0bGUgZ3JleVwiPk5ldyB2ZXJ0aWNsZSBsaW5lIGV2ZXJ5IHNlY29uZC4uLjwvaDI+XG48L2Rpdj5cIlwiXCJcbiJdLCJzb3VyY2VSb290IjoiIn0=
//# sourceURL=hero.coffee
