// Generated by CoffeeScript 2.4.1
"use strict";

(function () {
  document.getElementById('hero').innerHTML = "<div class=\"container\" id=\"logo\">\n<h1 class=\"title\">Vertical</h1>\n<h2 class=\"subtitle\">New verticle line every second...</h2>\n</div>";
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImhlcm8uY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztBQUFBLENBQUEsWUFBQTtBQUFBLEVBQUEsUUFBUSxDQUFSLGNBQUEsQ0FBQSxNQUFBLEVBQUEsU0FBQSxHQUE0QyxpSkFBNUM7Q0FBQSxFLElBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVybycpLmlubmVySFRNTCA9IFwiXCJcIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIiBpZD1cImxvZ29cIj5cbiAgPGgxIGNsYXNzPVwidGl0bGVcIj5WZXJ0aWNhbDwvaDE+XG4gIDxoMiBjbGFzcz1cInN1YnRpdGxlXCI+TmV3IHZlcnRpY2xlIGxpbmUgZXZlcnkgc2Vjb25kLi4uPC9oMj5cbjwvZGl2PlwiXCJcIlxuIl0sInNvdXJjZVJvb3QiOiIifQ==
//# sourceURL=hero.coffee
