"use strict";

// Generated by CoffeeScript 2.4.1
(function () {
  document.getElementById('hero').innerHTML = "<div class=\"container\" id=\"logo\">\n<h1 class=\"title grey\">Vertical</h1>\n<h2 class=\"subtitle grey\">Every second there is a new vertical line...</h2>\n</div>";
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImhlcm8uY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztBQUFBLENBQUEsWUFBQTtBQUFBLEVBQUEsUUFBUSxDQUFSLGNBQUEsQ0FBQSxNQUFBLEVBQUEsU0FBQSxHQUE0QyxzS0FBNUM7Q0FBQSxFLElBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVybycpLmlubmVySFRNTCA9IFwiXCJcIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIiBpZD1cImxvZ29cIj5cbiAgPGgxIGNsYXNzPVwidGl0bGUgZ3JleVwiPlZlcnRpY2FsPC9oMT5cbiAgPGgyIGNsYXNzPVwic3VidGl0bGUgZ3JleVwiPkV2ZXJ5IHNlY29uZCB0aGVyZSBpcyBhIG5ldyB2ZXJ0aWNhbCBsaW5lLi4uPC9oMj5cbjwvZGl2PlwiXCJcIlxuIl0sInNvdXJjZVJvb3QiOiIifQ==
//# sourceURL=hero.coffee
