// Generated by CoffeeScript 2.4.1
"use strict";

(function () {
  document.getElementById('nav').innerHTML = "<div class=\"container is-fluid\" style=\"padding-left: 1rem;padding-top: 1rem;\">\n<nav class=\"breadcrumb\">\n  <ul>\n    <li class=\"is-active\"><a href=\"https://github.com/Beyarz/vertical\">Github</a></li>\n    <li><a class=\"grey\" href=\"https://github.com/Beyarz/vertical\">Beyarz</a\"></li>\n  </ul>\n</nav>\n</div>";
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5hdi5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7O0FBQUEsQ0FBQSxZQUFBO0FBQUEsRUFBQSxRQUFRLENBQVIsY0FBQSxDQUFBLEtBQUEsRUFBQSxTQUFBLEdBQTJDLHNVQUEzQztDQUFBLEUsSUFBQSIsInNvdXJjZXNDb250ZW50IjpbImRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduYXYnKS5pbm5lckhUTUwgPSBcIlwiXCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGlzLWZsdWlkXCIgc3R5bGU9XCJwYWRkaW5nLWxlZnQ6IDFyZW07cGFkZGluZy10b3A6IDFyZW07XCI+XG4gIDxuYXYgY2xhc3M9XCJicmVhZGNydW1iXCI+XG4gICAgPHVsPlxuICAgICAgPGxpIGNsYXNzPVwiaXMtYWN0aXZlXCI+PGEgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovdmVydGljYWxcIj5HaXRodWI8L2E+PC9saT5cbiAgICAgIDxsaT48YSBjbGFzcz1cImdyZXlcIiBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL0JleWFyei92ZXJ0aWNhbFwiPkJleWFyejwvYVwiPjwvbGk+XG4gICAgPC91bD5cbiAgPC9uYXY+XG48L2Rpdj5cIlwiXCJcbiJdLCJzb3VyY2VSb290IjoiIn0=
//# sourceURL=nav.coffee
