// Generated by CoffeeScript 2.4.1
"use strict";

(function () {
  document.getElementById('nav').innerHTML = "<div class=\"container is-fluid\" style=\"padding-left: 1rem;padding-top: 1rem;\">\n<nav class=\"breadcrumb\">\n  <ul>\n    <li class=\"is-active\"><a href=\"https://github.com/Beyarz/vertical\">Github</a></li>\n    <li><a style=\"color:#e4e4e4;\" href=\"https://github.com/Beyarz/vertical\">Beyarz</a\"></li>\n  </ul>\n</nav>\n</div>";
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5hdi5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7O0FBQUEsQ0FBQSxZQUFBO0FBQUEsRUFBQSxRQUFRLENBQVIsY0FBQSxDQUFBLEtBQUEsRUFBQSxTQUFBLEdBQTJDLGdWQUEzQztDQUFBLEUsSUFBQSIsInNvdXJjZXNDb250ZW50IjpbImRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduYXYnKS5pbm5lckhUTUwgPSBcIlwiXCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGlzLWZsdWlkXCIgc3R5bGU9XCJwYWRkaW5nLWxlZnQ6IDFyZW07cGFkZGluZy10b3A6IDFyZW07XCI+XG4gIDxuYXYgY2xhc3M9XCJicmVhZGNydW1iXCI+XG4gICAgPHVsPlxuICAgICAgPGxpIGNsYXNzPVwiaXMtYWN0aXZlXCI+PGEgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovdmVydGljYWxcIj5HaXRodWI8L2E+PC9saT5cbiAgICAgIDxsaT48YSBzdHlsZT1cImNvbG9yOiNlNGU0ZTQ7XCIgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovdmVydGljYWxcIj5CZXlhcno8L2FcIj48L2xpPlxuICAgIDwvdWw+XG4gIDwvbmF2PlxuPC9kaXY+XCJcIlwiXG4iXSwic291cmNlUm9vdCI6IiJ9
//# sourceURL=nav.coffee
