"use strict";

// Generated by CoffeeScript 2.4.1
(function () {
  document.getElementById('nav').innerHTML = "<div class=\"container is-fluid\" style=\"padding-left: 1rem;padding-top: 1rem;\">\n<nav class=\"breadcrumb\">\n  <ul>\n    <li class=\"is-active\"><a style=\"color: #bebebe\" href=\"https://github.com/Beyarz/vertical\">Github</a></li>\n    <li><a style=\"color: rgb(220, 231, 255)\" href=\"https://github.com/Beyarz/vertical\">Beyarz</a></li>\n  </ul>\n</nav>\n</div>";
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5hdi5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7O0FBQUEsQ0FBQSxZQUFBO0FBQUEsRUFBQSxRQUFRLENBQVIsY0FBQSxDQUFBLEtBQUEsRUFBQSxTQUFBLEdBQTJDLGtYQUEzQztDQUFBLEUsSUFBQSIsInNvdXJjZXNDb250ZW50IjpbImRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduYXYnKS5pbm5lckhUTUwgPSBcIlwiXCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGlzLWZsdWlkXCIgc3R5bGU9XCJwYWRkaW5nLWxlZnQ6IDFyZW07cGFkZGluZy10b3A6IDFyZW07XCI+XG4gIDxuYXYgY2xhc3M9XCJicmVhZGNydW1iXCI+XG4gICAgPHVsPlxuICAgICAgPGxpIGNsYXNzPVwiaXMtYWN0aXZlXCI+PGEgc3R5bGU9XCJjb2xvcjogI2JlYmViZVwiIGhyZWY9XCJodHRwczovL2dpdGh1Yi5jb20vQmV5YXJ6L3ZlcnRpY2FsXCI+R2l0aHViPC9hPjwvbGk+XG4gICAgICA8bGk+PGEgc3R5bGU9XCJjb2xvcjogcmdiKDIyMCwgMjMxLCAyNTUpXCIgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovdmVydGljYWxcIj5CZXlhcno8L2E+PC9saT5cbiAgICA8L3VsPlxuICA8L25hdj5cbjwvZGl2PlwiXCJcIlxuIl0sInNvdXJjZVJvb3QiOiIifQ==
//# sourceURL=nav.coffee
