// Generated by CoffeeScript 2.4.1
"use strict";

(function () {
  var prepend;

  prepend = function prepend(id, content) {
    return document.getElementById(id).innerHTML = content;
  };

  prepend('nav', "<div class=\"container is-fluid\" style=\"padding-left:1rem;padding-top:1rem;\">\n<nav class=\"breadcrumb\">\n  <ul>\n    <li class=\"is-active\"><a href=\"https://github.com/Beyarz/vertical\">Github</a></li>\n    <li><a class=\"grey\" href=\"https://github.com/Beyarz/vertical\">Beyarz</a\"></li>\n  </ul>\n</nav>\n</div>");
  prepend('hero', "<div class=\"container\" id=\"logo\">\n<h1 class=\"title\">Vertical</h1>\n<h2 class=\"subtitle\">New verticle line every second...</h2>\n</div>");
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInByZXBlbmQuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztBQUFBLENBQUEsWUFBQTtBQUFBLE1BQUEsT0FBQTs7QUFBQSxFQUFBLE9BQUEsR0FBVSxpQkFBQSxFQUFBLEVBQUEsT0FBQSxFQUFBO1dBQ1IsUUFBUSxDQUFSLGNBQUEsQ0FBQSxFQUFBLEVBQUEsU0FBQSxHQUF3QyxPO0FBRGhDLEdBQVY7O0FBR0EsRUFBQSxPQUFBLENBQUEsS0FBQSxFQUFBLG9VQUFBLENBQUE7QUFXQSxFQUFBLE9BQUEsQ0FBQSxNQUFBLEVBQUEsaUpBQUEsQ0FBQTtDQWRBLEUsSUFBQSIsInNvdXJjZXNDb250ZW50IjpbInByZXBlbmQgPSAoaWQsIGNvbnRlbnQpID0+XG4gIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlkKS5pbm5lckhUTUwgPSBjb250ZW50XG5cbnByZXBlbmQoJ25hdicsXG5cIlwiXCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGlzLWZsdWlkXCIgc3R5bGU9XCJwYWRkaW5nLWxlZnQ6MXJlbTtwYWRkaW5nLXRvcDoxcmVtO1wiPlxuICA8bmF2IGNsYXNzPVwiYnJlYWRjcnVtYlwiPlxuICAgIDx1bD5cbiAgICAgIDxsaSBjbGFzcz1cImlzLWFjdGl2ZVwiPjxhIGhyZWY9XCJodHRwczovL2dpdGh1Yi5jb20vQmV5YXJ6L3ZlcnRpY2FsXCI+R2l0aHViPC9hPjwvbGk+XG4gICAgICA8bGk+PGEgY2xhc3M9XCJncmV5XCIgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovdmVydGljYWxcIj5CZXlhcno8L2FcIj48L2xpPlxuICAgIDwvdWw+XG4gIDwvbmF2PlxuPC9kaXY+XCJcIlwiXG4pXG5cbnByZXBlbmQoJ2hlcm8nLFxuXCJcIlwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiIGlkPVwibG9nb1wiPlxuICA8aDEgY2xhc3M9XCJ0aXRsZVwiPlZlcnRpY2FsPC9oMT5cbiAgPGgyIGNsYXNzPVwic3VidGl0bGVcIj5OZXcgdmVydGljbGUgbGluZSBldmVyeSBzZWNvbmQuLi48L2gyPlxuPC9kaXY+XCJcIlwiXG4pXG4iXSwic291cmNlUm9vdCI6IiJ9
//# sourceURL=prepend.coffee
